package com.example.spring_boot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin(origins = "http://localhost:5173")
@RestController
public class SaleController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;
    @Autowired
    private SaleRepository saleRepository;

    @GetMapping("/api/getProducts")
    public @ResponseBody Iterable<Product> getProducts() {
        // This returns a JSON or XML with the users
        return productRepository.findAll();
    }

    @GetMapping("/api/getSales")
    public @ResponseBody Iterable<Sale> getSales() {
        // This returns a JSON or XML with the users
        return saleRepository.findAll();
    }

}